### PR TITLE
adding logo

### PR DESCRIPTION
**Pull request by kvndlgs**
### Outlined
logo-outline

### Grayscale
logo-grayscale

### Logo
logo

Greetings, here's what I've crafted so far, let me know if there is any modifications needed.

### CODE REVIEW

**Comment by cryptogoth** [comment]
Great work! I especially appreciate the different versions ( wireframe, solid color)
My main feedback is that it looks like a single pipe.
For a tip, Is there a way to give a sense of multiple pipes, ending in Ethereum, rather than Ethereum inside?

**Comment by kvndlgs** [comment]
Thank you. As if the pipes were connected to it?

**Comment by cryptogoth** [comment]
After more thought, in the same style and re-using your work above,
can you make a more horizontal pipe viewed 3/4 from the side, like a play-doh-like extruder, a single hole in the shape of the Ethereum logo ? Thank you

image

**Comment by cryptogoth** [comment]
please keep your pipe style by the way, with concentric circles and a transparent, glass-like texture.
I don't want it to have finger grips or a plastic-y look of the play-doh, just the idea of extrusion

**Comment by kvndlgs** [comment]
Are these closer to what you had in mind?

[image: v2.jpg]

**Comment by cryptogoth** [comment]
I didn't see a file attached in your last post. Perhaps the markdown got mangled or the file never uploaded?

**Comment by kvndlgs** [comment]
I'm sorry, it seems like files don't send when replied directly from Gmail.

v2

**Comment by cryptogoth** [comment]
These are amazing and what I had in mind.
If you can commit the SVG images, I'd like to merge and close out this bounty, and then work with you on future refinements in later bounties.

**Comment by kvndlgs** [comment]
Great, thank you. I have pushed the latest commit.

**Pull request merged**
